version: 2
updates:
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
      timezone: Europe/London
  - package-ecosystem: npm
    directory: "/assets"
    ignore:
      - dependency-name: "phoenix"
      - dependency-name: "phoenix_html"
      - dependency-name: "phoenix_live_view"
    schedule:
      interval: daily
      time: "07:00"
      timezone: Europe/London
